In [1]:
import numpy as np

In [2]:
array=np.array([1,2,3,4,5,6,7])

In [3]:
array

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
array*2

array([ 2,  4,  6,  8, 10, 12, 14])

In [5]:
array-2

array([-1,  0,  1,  2,  3,  4,  5])

In [6]:
array+33

array([34, 35, 36, 37, 38, 39, 40])

In [7]:
array/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [8]:
array%2

array([1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [9]:
array+3-2

array([2, 3, 4, 5, 6, 7, 8])

In [10]:
array[2]

3

In [11]:
array[4]+array[6]

12

In [12]:
array[0:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
array[2:]

array([3, 4, 5, 6, 7])

In [14]:
array[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
array2=np.array([10,11,12,13,14,15,16])

In [16]:
array+array2

array([11, 13, 15, 17, 19, 21, 23])

In [17]:
array-array2

array([-9, -9, -9, -9, -9, -9, -9])

In [18]:
array2-array

array([9, 9, 9, 9, 9, 9, 9])

In [19]:
array*array2

array([ 10,  22,  36,  52,  70,  90, 112])

In [20]:
array/array2

array([0.1       , 0.18181818, 0.25      , 0.30769231, 0.35714286,
       0.4       , 0.4375    ])

In [21]:
array2/array

array([10.        ,  5.5       ,  4.        ,  3.25      ,  2.8       ,
        2.5       ,  2.28571429])

In [22]:
array%array2

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
array2%array

array([0, 1, 0, 1, 4, 3, 2])

In [24]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
matrix2=np.array([[9,8,7],[6,5,4],[3,2,1]])

In [27]:
matrix2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [28]:
matrix+matrix2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [29]:
matrix-matrix2

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [30]:
matrix2-matrix

array([[ 8,  6,  4],
       [ 2,  0, -2],
       [-4, -6, -8]])

In [31]:
matrix*matrix2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [32]:
matrix.dot(matrix2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [33]:
matrix.dot(matrix)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [34]:
matrix>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [35]:
matrix==2

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [36]:
matrix!=1

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
matrix2<2

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [38]:
matrix3=np.array([['not','only','such'],['much','touch','more'],['less','least','low']])

In [39]:
matrix3=='such'

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [40]:
matrix3>'like'

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [41]:
matrix3!='low'

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [42]:
'ch' in matrix3[1][1]

True

In [43]:
matrix3[matrix3>'like']

array(['not', 'only', 'such', 'much', 'touch', 'more', 'low'], dtype='<U5')

In [44]:
matrix3[matrix3=='such']

array(['such'], dtype='<U5')

In [45]:
matrix3[matrix3>'a']

array(['not', 'only', 'such', 'much', 'touch', 'more', 'less', 'least',
       'low'], dtype='<U5')

In [46]:
matrix3[matrix3>'s']

array(['such', 'touch'], dtype='<U5')

In [47]:
matrix3[matrix3<'s']

array(['not', 'only', 'much', 'more', 'less', 'least', 'low'], dtype='<U5')

In [48]:
matrix3[matrix3<='Z']

array([], dtype='<U5')

In [49]:
matrix3[matrix3!='a']

array(['not', 'only', 'such', 'much', 'touch', 'more', 'less', 'least',
       'low'], dtype='<U5')

In [50]:
matrix3[matrix3==matrix3]

array(['not', 'only', 'such', 'much', 'touch', 'more', 'less', 'least',
       'low'], dtype='<U5')

In [51]:
matrix.mean()

5.0

In [52]:
matrix.max()

9

In [53]:
matrix.min()

1

In [56]:
matrix4=np.array([['not','onlyi','such'],['much','touchi','more'],['less','leasti','low']])

In [57]:
matrix3[matrix3==matrix4]

array(['not', 'such', 'much', 'more', 'less', 'low'], dtype='<U5')

In [4]:
arr=np.array([[0,0,0],[0,0,0],[0,0,0]])

In [2]:
arr1=np.random.rand(5,5)

In [3]:
arr1

array([[0.38916203, 0.65199318, 0.72618431, 0.81739316, 0.94359711],
       [0.74219622, 0.8376035 , 0.78741483, 0.06088337, 0.96245944],
       [0.24002894, 0.05909407, 0.05094441, 0.14672017, 0.20703803],
       [0.96293527, 0.91096557, 0.55206279, 0.88967281, 0.66912518],
       [0.041912  , 0.31119161, 0.10777383, 0.12794646, 0.21291718]])

In [5]:
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
zarr=np.zeros((3,3))

In [8]:
zarr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
one_arr=np.ones((4,4))

In [10]:
one_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
Identity_matrix=np.eye(5)

In [12]:
Identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
a1=np.array([2,3,4,5])

In [25]:
a1

array([2, 3, 4, 5])

In [27]:
a2=np.array([[2,4,6,8],[1,3,5,6]])

In [28]:
a2

array([[2, 4, 6, 8],
       [1, 3, 5, 6]])

In [29]:
a3=np.array([[[2,3,4],[5,6,7]],[[8,9,0],[1,23,4]]])

In [30]:
a3

array([[[ 2,  3,  4],
        [ 5,  6,  7]],

       [[ 8,  9,  0],
        [ 1, 23,  4]]])

In [34]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.amin(a3)

0

In [36]:
np.amax(a3)

23

In [37]:
np.abs(a3)

array([[[ 2,  3,  4],
        [ 5,  6,  7]],

       [[ 8,  9,  0],
        [ 1, 23,  4]]])

In [70]:
a22=np.arange(1,101).reshape(10,10)

In [71]:
a22

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [72]:
a33=np.arange(1,401).reshape(4,10,10)

In [73]:
a33

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]],

       [[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
        [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
        [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
        [161, 162, 163, 164, 165, 166,

In [74]:
a33.ndim

3

In [75]:
a22.ndim

2

In [76]:
a11=np.arange(10)

In [77]:
a11

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
a11.ndim

1

In [59]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
a11.shape

(10,)

In [61]:
a22.shape

(10, 10)

In [62]:
a33.shape

(4, 10, 10)

In [63]:
a33.dtype

dtype('int32')

In [64]:
a22.dtype

dtype('int32')

In [65]:
a11.size

10

In [66]:
a22.size

100

In [67]:
a11.itemsize

4

In [68]:
a22.itemsize

4

In [78]:
a33.itemsize

4

In [79]:
a33.nbytes

1600

In [80]:
a22.nbytes

400

In [81]:
a11.real

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a22.real

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [83]:
a33.real

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]],

       [[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
        [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
        [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
        [161, 162, 163, 164, 165, 166,

In [85]:
a11.imag

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [86]:
a22.imag

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [87]:
a33.imag

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [96]:
a111=np.arange(10)

In [97]:
a11.dot(a111)

285

In [98]:
a222=np.arange(101,201).reshape(10,10)

In [99]:
a22.dot(a222)

array([[  8855,   8910,   8965,   9020,   9075,   9130,   9185,   9240,
          9295,   9350],
       [ 23455,  23610,  23765,  23920,  24075,  24230,  24385,  24540,
         24695,  24850],
       [ 38055,  38310,  38565,  38820,  39075,  39330,  39585,  39840,
         40095,  40350],
       [ 52655,  53010,  53365,  53720,  54075,  54430,  54785,  55140,
         55495,  55850],
       [ 67255,  67710,  68165,  68620,  69075,  69530,  69985,  70440,
         70895,  71350],
       [ 81855,  82410,  82965,  83520,  84075,  84630,  85185,  85740,
         86295,  86850],
       [ 96455,  97110,  97765,  98420,  99075,  99730, 100385, 101040,
        101695, 102350],
       [111055, 111810, 112565, 113320, 114075, 114830, 115585, 116340,
        117095, 117850],
       [125655, 126510, 127365, 128220, 129075, 129930, 130785, 131640,
        132495, 133350],
       [140255, 141210, 142165, 143120, 144075, 145030, 145985, 146940,
        147895, 148850]])

In [100]:
a222.dot(a22)

array([[ 49355,  50410,  51465,  52520,  53575,  54630,  55685,  56740,
         57795,  58850],
       [ 53955,  55110,  56265,  57420,  58575,  59730,  60885,  62040,
         63195,  64350],
       [ 58555,  59810,  61065,  62320,  63575,  64830,  66085,  67340,
         68595,  69850],
       [ 63155,  64510,  65865,  67220,  68575,  69930,  71285,  72640,
         73995,  75350],
       [ 67755,  69210,  70665,  72120,  73575,  75030,  76485,  77940,
         79395,  80850],
       [ 72355,  73910,  75465,  77020,  78575,  80130,  81685,  83240,
         84795,  86350],
       [ 76955,  78610,  80265,  81920,  83575,  85230,  86885,  88540,
         90195,  91850],
       [ 81555,  83310,  85065,  86820,  88575,  90330,  92085,  93840,
         95595,  97350],
       [ 86155,  88010,  89865,  91720,  93575,  95430,  97285,  99140,
        100995, 102850],
       [ 90755,  92710,  94665,  96620,  98575, 100530, 102485, 104440,
        106395, 108350]])

In [101]:
a11**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [103]:
a22**2

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [104]:
a22>15

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [105]:
a11+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [106]:
a22-50

array([[-49, -48, -47, -46, -45, -44, -43, -42, -41, -40],
       [-39, -38, -37, -36, -35, -34, -33, -32, -31, -30],
       [-29, -28, -27, -26, -25, -24, -23, -22, -21, -20],
       [-19, -18, -17, -16, -15, -14, -13, -12, -11, -10],
       [ -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50]])

In [108]:
print(a22[9][8])

99


In [109]:
a22/2

array([[ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ],
       [15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ],
       [20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. ],
       [25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. ],
       [30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5, 34. , 34.5, 35. ],
       [35.5, 36. , 36.5, 37. , 37.5, 38. , 38.5, 39. , 39.5, 40. ],
       [40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5, 44. , 44.5, 45. ],
       [45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. , 49.5, 50. ]])

In [110]:
a22//2

array([[ 0,  1,  1,  2,  2,  3,  3,  4,  4,  5],
       [ 5,  6,  6,  7,  7,  8,  8,  9,  9, 10],
       [10, 11, 11, 12, 12, 13, 13, 14, 14, 15],
       [15, 16, 16, 17, 17, 18, 18, 19, 19, 20],
       [20, 21, 21, 22, 22, 23, 23, 24, 24, 25],
       [25, 26, 26, 27, 27, 28, 28, 29, 29, 30],
       [30, 31, 31, 32, 32, 33, 33, 34, 34, 35],
       [35, 36, 36, 37, 37, 38, 38, 39, 39, 40],
       [40, 41, 41, 42, 42, 43, 43, 44, 44, 45],
       [45, 46, 46, 47, 47, 48, 48, 49, 49, 50]], dtype=int32)

In [111]:
a22*0.5

array([[ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ],
       [15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ],
       [20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. ],
       [25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. ],
       [30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5, 34. , 34.5, 35. ],
       [35.5, 36. , 36.5, 37. , 37.5, 38. , 38.5, 39. , 39.5, 40. ],
       [40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5, 44. , 44.5, 45. ],
       [45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. , 49.5, 50. ]])

In [112]:
(a11+5)+(a11-5)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [113]:
a22+(-100)

array([[-99, -98, -97, -96, -95, -94, -93, -92, -91, -90],
       [-89, -88, -87, -86, -85, -84, -83, -82, -81, -80],
       [-79, -78, -77, -76, -75, -74, -73, -72, -71, -70],
       [-69, -68, -67, -66, -65, -64, -63, -62, -61, -60],
       [-59, -58, -57, -56, -55, -54, -53, -52, -51, -50],
       [-49, -48, -47, -46, -45, -44, -43, -42, -41, -40],
       [-39, -38, -37, -36, -35, -34, -33, -32, -31, -30],
       [-29, -28, -27, -26, -25, -24, -23, -22, -21, -20],
       [-19, -18, -17, -16, -15, -14, -13, -12, -11, -10],
       [ -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0]])

In [114]:
a22>=50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [115]:
a22==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [116]:
a22!=50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [119]:
a22==a33

array([[[ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True],
        [ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True]],

       [[False, False, False, False, False, False, False, False, False,
         False],
        [False, Fal

In [120]:
a11==a22

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [122]:
a22==a222

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [123]:
100 in a22

True

In [124]:
a11[2]=33

In [125]:
a11

array([ 0,  1, 33,  3,  4,  5,  6,  7,  8,  9])

In [126]:
a11[9]

9

In [127]:
a11[9]=a11[2]
a11[2]=a22[9][9]

In [128]:
a11

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,  33])

In [129]:
print(a11[0:])

[  0   1 100   3   4   5   6   7   8  33]


In [130]:
a22[0:][0:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [137]:
a22[:8]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [138]:
a11[2]-a11[3]

97

In [139]:
a22[3]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [140]:
a22[4:8]

array([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [141]:
a22[3,3]

34

In [142]:
a22[0,5]

6

In [145]:
a22[0:,2:5]

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25],
       [33, 34, 35],
       [43, 44, 45],
       [53, 54, 55],
       [63, 64, 65],
       [73, 74, 75],
       [83, 84, 85],
       [93, 94, 95]])

In [146]:
a22[2:,3:9]

array([[24, 25, 26, 27, 28, 29],
       [34, 35, 36, 37, 38, 39],
       [44, 45, 46, 47, 48, 49],
       [54, 55, 56, 57, 58, 59],
       [64, 65, 66, 67, 68, 69],
       [74, 75, 76, 77, 78, 79],
       [84, 85, 86, 87, 88, 89],
       [94, 95, 96, 97, 98, 99]])

In [149]:
a22[2:4,6:8]

array([[27, 28],
       [37, 38]])

In [150]:
a22[3:6,:3]

array([[31, 32, 33],
       [41, 42, 43],
       [51, 52, 53]])

In [151]:
a22[:3,:3]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [152]:
a22[:5,:2]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42]])

In [153]:
a22[:2,:5]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [154]:
a22[6:9,3:6]

array([[64, 65, 66],
       [74, 75, 76],
       [84, 85, 86]])

In [156]:
a33[:4,:3,:2]

array([[[  1,   2],
        [ 11,  12],
        [ 21,  22]],

       [[101, 102],
        [111, 112],
        [121, 122]],

       [[201, 202],
        [211, 212],
        [221, 222]],

       [[301, 302],
        [311, 312],
        [321, 322]]])

In [162]:
a33[1:4,1:2,1:2]

array([[[112]],

       [[212]],

       [[312]]])

In [163]:
a33[:5,2:4,2:4]

array([[[ 23,  24],
        [ 33,  34]],

       [[123, 124],
        [133, 134]],

       [[223, 224],
        [233, 234]],

       [[323, 324],
        [333, 334]]])

In [165]:
a33[0:,4:6,5:6]

array([[[ 46],
        [ 56]],

       [[146],
        [156]],

       [[246],
        [256]],

       [[346],
        [356]]])

In [166]:
a33[0:,4:5,4:6]

array([[[ 45,  46]],

       [[145, 146]],

       [[245, 246]],

       [[345, 346]]])

In [167]:
a33[3:3,2:,2:]

array([], shape=(0, 8, 8), dtype=int32)

In [168]:
a33[1:,0:0,1:]

array([], shape=(3, 0, 9), dtype=int32)

In [169]:
a33[1:,1:,5:5]

array([], shape=(3, 9, 0), dtype=int32)

In [175]:
a33[:,3:4,:]

array([[[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40]],

       [[131, 132, 133, 134, 135, 136, 137, 138, 139, 140]],

       [[231, 232, 233, 234, 235, 236, 237, 238, 239, 240]],

       [[331, 332, 333, 334, 335, 336, 337, 338, 339, 340]]])

In [174]:
a33[:,:,2:3]

array([[[  3],
        [ 13],
        [ 23],
        [ 33],
        [ 43],
        [ 53],
        [ 63],
        [ 73],
        [ 83],
        [ 93]],

       [[103],
        [113],
        [123],
        [133],
        [143],
        [153],
        [163],
        [173],
        [183],
        [193]],

       [[203],
        [213],
        [223],
        [233],
        [243],
        [253],
        [263],
        [273],
        [283],
        [293]],

       [[303],
        [313],
        [323],
        [333],
        [343],
        [353],
        [363],
        [373],
        [383],
        [393]]])

In [176]:
a33[2:3,:,:]

array([[[201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
        [211, 212, 213, 214, 215, 216, 217, 218, 219, 220],
        [221, 222, 223, 224, 225, 226, 227, 228, 229, 230],
        [231, 232, 233, 234, 235, 236, 237, 238, 239, 240],
        [241, 242, 243, 244, 245, 246, 247, 248, 249, 250],
        [251, 252, 253, 254, 255, 256, 257, 258, 259, 260],
        [261, 262, 263, 264, 265, 266, 267, 268, 269, 270],
        [271, 272, 273, 274, 275, 276, 277, 278, 279, 280],
        [281, 282, 283, 284, 285, 286, 287, 288, 289, 290],
        [291, 292, 293, 294, 295, 296, 297, 298, 299, 300]]])

In [172]:
a22[:2,1:4]

array([[ 2,  3,  4],
       [12, 13, 14]])

In [173]:
a22[1:3,1:3]

array([[12, 13],
       [22, 23]])

In [178]:
a33[a33>150]

array([151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
       164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176,
       177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
       190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
       203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
       216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
       229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
       242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
       255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267,
       268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280,
       281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293,
       294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306,
       307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319,
       320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 33

In [201]:
a22[a22>40]

array([ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])

In [202]:
a22[~(a22>40)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [224]:
mark=a22>40

In [225]:
a22[~mark]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [205]:
mark1=~mark

In [206]:
a22[mark1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [217]:
mark1=(a22<30)

In [218]:
a22[mark1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [285]:
a2=np.arange(12).reshape(4,3)

In [286]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [287]:
mar=a2>3

In [288]:
a2[mar]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [289]:
mar1=a2<3

In [290]:
a2[mar1]

array([0, 1, 2])

In [291]:
mar2=a2!=5

In [292]:
a2[mar2]

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [293]:
a21=a2.reshape(3,4)

In [294]:
a21[0,0]=12

In [295]:
a21

array([[12,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [251]:
a21[:,1:3]=0

In [252]:
a21

array([[12,  0,  0,  3],
       [ 4,  0,  0,  7],
       [ 8,  0,  0, 11]])

In [253]:
a21[1:2,:]=0

In [254]:
a21

array([[12,  0,  0,  3],
       [ 0,  0,  0,  0],
       [ 8,  0,  0, 11]])

In [255]:
a21[1:2,:]=22

In [256]:
a21

array([[12,  0,  0,  3],
       [22, 22, 22, 22],
       [ 8,  0,  0, 11]])

In [257]:
a21[:,1:3]=33

In [258]:
a21

array([[12, 33, 33,  3],
       [22, 33, 33, 22],
       [ 8, 33, 33, 11]])

In [259]:
a21[:,0:1]=11

In [260]:
a21

array([[11, 33, 33,  3],
       [11, 33, 33, 22],
       [11, 33, 33, 11]])

In [261]:
a21[:,3:]=22

In [262]:
a21

array([[11, 33, 33, 22],
       [11, 33, 33, 22],
       [11, 33, 33, 22]])

In [263]:
a21[1:2,:]=44

In [264]:
a21

array([[11, 33, 33, 22],
       [44, 44, 44, 44],
       [11, 33, 33, 22]])

In [265]:
a21[2:,:]=55

In [266]:
a21

array([[11, 33, 33, 22],
       [44, 44, 44, 44],
       [55, 55, 55, 55]])

In [267]:
a21[0:1,:]=33

In [268]:
a21

array([[33, 33, 33, 33],
       [44, 44, 44, 44],
       [55, 55, 55, 55]])

In [274]:
a21[a21>33]=33

In [275]:
a21

array([[33, 33, 33, 33],
       [33, 33, 33, 33],
       [33, 33, 33, 33]])

In [276]:
ai=a21==33

In [278]:
a21[ai]='00'

In [279]:
a21

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [282]:
a21=a21+100

In [283]:
a21

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [307]:
a211=np.arange(33).reshape(3,11)

In [309]:
a211

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

In [310]:
a211[(a211>3)&(a211<13)]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [316]:
a211[(a211<25)&(a211>=8)]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [317]:
a211[(a211%2==0)&(a211>5)]

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [321]:
a211[((a211%2)!=0)&(a211<20)]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [322]:
np.sort(a211,axis=0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

In [324]:
a=np.random.rand(5,5)

In [325]:
a

array([[0.64864673, 0.14268127, 0.47702419, 0.520071  , 0.93924812],
       [0.72590627, 0.52666273, 0.40326469, 0.47346386, 0.81924115],
       [0.13926519, 0.36256693, 0.36612691, 0.22960681, 0.77073071],
       [0.1075132 , 0.44414502, 0.53049892, 0.91696875, 0.99745884],
       [0.0203411 , 0.18945711, 0.17115439, 0.57232116, 0.06094221]])

In [326]:
np.sort(a,axis=0)

array([[0.0203411 , 0.14268127, 0.17115439, 0.22960681, 0.06094221],
       [0.1075132 , 0.18945711, 0.36612691, 0.47346386, 0.77073071],
       [0.13926519, 0.36256693, 0.40326469, 0.520071  , 0.81924115],
       [0.64864673, 0.44414502, 0.47702419, 0.57232116, 0.93924812],
       [0.72590627, 0.52666273, 0.53049892, 0.91696875, 0.99745884]])

In [327]:
np.sort(a,axis=1)

array([[0.14268127, 0.47702419, 0.520071  , 0.64864673, 0.93924812],
       [0.40326469, 0.47346386, 0.52666273, 0.72590627, 0.81924115],
       [0.13926519, 0.22960681, 0.36256693, 0.36612691, 0.77073071],
       [0.1075132 , 0.44414502, 0.53049892, 0.91696875, 0.99745884],
       [0.0203411 , 0.06094221, 0.17115439, 0.18945711, 0.57232116]])

In [328]:
a #sorted array will not make any changes in original array

array([[0.64864673, 0.14268127, 0.47702419, 0.520071  , 0.93924812],
       [0.72590627, 0.52666273, 0.40326469, 0.47346386, 0.81924115],
       [0.13926519, 0.36256693, 0.36612691, 0.22960681, 0.77073071],
       [0.1075132 , 0.44414502, 0.53049892, 0.91696875, 0.99745884],
       [0.0203411 , 0.18945711, 0.17115439, 0.57232116, 0.06094221]])

In [341]:
c=np.arange(5,11).reshape(3,2)
c1=np.arange(11,17).reshape(3,2)

In [342]:
c

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [343]:
c1

array([[11, 12],
       [13, 14],
       [15, 16]])

In [346]:
np.concatenate(c1)

array([11, 12, 13, 14, 15, 16])

In [347]:
np.append(c,c1)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])