In [1]:
import numpy as np
a=[1,2,3,4,5]
b=[10,9,8,7,6]
r=(np.array(a)+np.array(b))
r

array([11, 11, 11, 11, 11])

In [2]:
r*6

array([66, 66, 66, 66, 66])

In [3]:
mat=np.array([[1,2,3],[9,8,7],[7,8,9]])
mat1=np.array([[34,8,7],[7,12,9],[32,15,1]])
z=mat+mat1
z

array([[35, 10, 10],
       [16, 20, 16],
       [39, 23, 10]])

z*5

In [4]:
z*10

array([[350, 100, 100],
       [160, 200, 160],
       [390, 230, 100]])

In [5]:
print(z>10,z<10,z!=10,z==10,z|10,z<<10,z+z,z>=z)

[[ True False False]
 [ True  True  True]
 [ True  True False]] [[False False False]
 [False False False]
 [False False False]] [[ True False False]
 [ True  True  True]
 [ True  True False]] [[False  True  True]
 [False False False]
 [False False  True]] [[43 10 10]
 [26 30 26]
 [47 31 10]] [[35840 10240 10240]
 [16384 20480 16384]
 [39936 23552 10240]] [[70 20 20]
 [32 40 32]
 [78 46 20]] [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [6]:
z

array([[35, 10, 10],
       [16, 20, 16],
       [39, 23, 10]])

In [7]:
a=z[z>10]
a

array([35, 16, 20, 16, 39, 23])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.random.rand(4,4)

array([[0.38921397, 0.18932518, 0.45193562, 0.68739684],
       [0.88019673, 0.42768054, 0.3205066 , 0.91925049],
       [0.92012406, 0.43458855, 0.05503441, 0.6925856 ],
       [0.48752017, 0.93958972, 0.25001859, 0.6684457 ]])

In [11]:
a=([[1,2,3],
   [9,8,7]])
a

[[1, 2, 3], [9, 8, 7]]

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
n=np.array([[1,2,5,6],
          [3,4,7,8],
            [5,8,3,7]])
n.ndim

2

In [16]:
n.shape

(3, 4)

In [17]:
n.dtype

dtype('int32')

In [18]:
n.size

12

In [19]:
n.itemsize

4

In [20]:
n.nbytes

48

In [21]:
n.real

array([[1, 2, 5, 6],
       [3, 4, 7, 8],
       [5, 8, 3, 7]])

In [22]:
n.imag

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
n.transpose

<function ndarray.transpose>

In [24]:
n.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [25]:
n.base

In [26]:
n**2

array([[ 1,  4, 25, 36],
       [ 9, 16, 49, 64],
       [25, 64,  9, 49]])

In [27]:
n>3

array([[False, False,  True,  True],
       [False,  True,  True,  True],
       [ True,  True, False,  True]])

In [28]:
n==3

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False,  True, False]])

In [29]:
n>=5

array([[False, False,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False,  True]])

In [30]:
n!=7

array([[ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [31]:
n<=3

array([[ True,  True, False, False],
       [ True, False, False, False],
       [False, False,  True, False]])

In [32]:
~n

array([[-2, -3, -6, -7],
       [-4, -5, -8, -9],
       [-6, -9, -4, -8]])

In [33]:
l=np.array([1,2,3,4,5,6,7,8,9,45,354,547,36,563,99])
print(l[6],l[2:8])
l[1:8]

7 [3 4 5 6 7 8]


array([2, 3, 4, 5, 6, 7, 8])

In [34]:
l[1:10:2]

array([ 2,  4,  6,  8, 45])

In [35]:
n[:,:]

array([[1, 2, 5, 6],
       [3, 4, 7, 8],
       [5, 8, 3, 7]])

In [36]:
n[1,3]

8

In [37]:
n[1:3,1:3]

array([[4, 7],
       [8, 3]])

In [38]:
n[2:3,1:2]

array([[8]])

In [39]:
n[1:2,2:3]

array([[7]])

In [40]:
l

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  45, 354, 547,  36,
       563,  99])

In [41]:
a=l>50
l[a]

array([354, 547, 563,  99])

In [42]:
a=~(l>100)
l[a]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 45, 36, 99])

In [43]:
n

array([[1, 2, 5, 6],
       [3, 4, 7, 8],
       [5, 8, 3, 7]])

In [44]:
mask=~(n>=3)
n[mask]

array([1, 2])

In [45]:
mask=n==3
n[mask]

array([3, 3])

In [46]:
mask=~(n==7)
n[mask]

array([1, 2, 5, 6, 3, 4, 8, 5, 8, 3])

In [47]:
mask=n!=7
n[mask]

array([1, 2, 5, 6, 3, 4, 8, 5, 8, 3])

In [48]:
mask=~(n!=7)
n[mask]

array([7, 7])

In [49]:
print(l)
l[2]=999
l

[  1   2   3   4   5   6   7   8   9  45 354 547  36 563  99]


array([  1,   2, 999,   4,   5,   6,   7,   8,   9,  45, 354, 547,  36,
       563,  99])

In [50]:
#assign by slicing in 1-D
l[3:6]=7
l

array([  1,   2, 999,   7,   7,   7,   7,   8,   9,  45, 354, 547,  36,
       563,  99])

In [51]:
print(n)
n[0,2]=17
n[2,1]=99
n[1,2]=14
n

[[1 2 5 6]
 [3 4 7 8]
 [5 8 3 7]]


array([[ 1,  2, 17,  6],
       [ 3,  4, 14,  8],
       [ 5, 99,  3,  7]])

In [52]:
#Assignment of value by slicing in 2-D
print(n)
n[1:2,2:3]=21
n[0:1,0:1]=15
n[0:1,1:2]=22
n[1:2,1:3]=44
n[2:3,2:4]=55
n

[[ 1  2 17  6]
 [ 3  4 14  8]
 [ 5 99  3  7]]


array([[15, 22, 17,  6],
       [ 3, 44, 44,  8],
       [ 5, 99, 55, 55]])

In [53]:
print(l)
mask=l==7
l[mask]=55
l

[  1   2 999   7   7   7   7   8   9  45 354 547  36 563  99]


array([  1,   2, 999,  55,  55,  55,  55,   8,   9,  45, 354, 547,  36,
       563,  99])

In [54]:
mask=l>=777
l[mask]=88
l

array([  1,   2,  88,  55,  55,  55,  55,   8,   9,  45, 354, 547,  36,
       563,  99])

In [55]:
print(n)
mask=n>=55
n[mask]=77
n

[[15 22 17  6]
 [ 3 44 44  8]
 [ 5 99 55 55]]


array([[15, 22, 17,  6],
       [ 3, 44, 44,  8],
       [ 5, 77, 77, 77]])

In [56]:
mask=n==77
n[mask]=256
n

array([[ 15,  22,  17,   6],
       [  3,  44,  44,   8],
       [  5, 256, 256, 256]])

In [57]:
mask=((n>200)&(n%2==0))
n[mask]=67
n

array([[15, 22, 17,  6],
       [ 3, 44, 44,  8],
       [ 5, 67, 67, 67]])

In [58]:
mask=((n>=10)&(n%2!=0))
n[mask]=45
n

array([[45, 22, 45,  6],
       [ 3, 44, 44,  8],
       [ 5, 45, 45, 45]])

In [59]:
b=np.random.randint(2.0,50.0,30).reshape(6,5)
b

array([[41, 49, 18, 33, 39],
       [ 4, 35, 28, 23, 17],
       [16, 48, 46, 27, 16],
       [15, 41, 45, 34,  9],
       [28,  8,  7, 27, 22],
       [34,  6,  9,  9, 15]])

In [60]:
a=np.sort(b,axis=0)   # 0 for y axis 
#a2=a1+a
a

array([[ 4,  6,  7,  9,  9],
       [15,  8,  9, 23, 15],
       [16, 35, 18, 27, 16],
       [28, 41, 28, 27, 17],
       [34, 48, 45, 33, 22],
       [41, 49, 46, 34, 39]])

In [63]:
a1=np.sort(a,axis=1)  # 1 for x axis
a1

array([[ 4,  6,  7,  9,  9],
       [ 8,  9, 15, 15, 23],
       [16, 16, 18, 27, 35],
       [17, 27, 28, 28, 41],
       [22, 33, 34, 45, 48],
       [34, 39, 41, 46, 49]])