<a href="https://colab.research.google.com/github/AdilGhub/pycode/blob/main/pycode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

#compound Interest
import math
pj1=float(input("Adil Enter principle Amount"))
rj1=float(input("Adil Enter the rate of Interest"))
tj1=float(input("Adil Enter Time period in years"))
amt=pj1*(math.pow((1+(rj1/100)),tj1))
print ("Compound Amount :",amt)
CI=amt-pj1
print(CI)

Adil Enter principle Amount1000
Adil Enter the rate of Interest10
Adil Enter Time period in years1
Compound Amount : 1100.0
100.0


In [ ]:
#Distance between two points
j1=int(input("Adil Enter j1:"))
j2=int(input("Adil Enter j2:"))
i1=int(input("Adil Enter i1:"))
i2=int(input("Adil Enter i2:"))
result=((((j2-j1)**2)+((i2-i1)**2))**0.5)
print("Distance between ",(j1,j2),"and",(i1,i2),"is:", result)

Adil Enter j1:5
Adil Enter j2:7
Adil Enter i1:2
Adil Enter i2:9
Distance between  (5, 7) and (2, 9) is: 7.280109889280518


In [ ]:
#format
name,age="Adil",19
address="wanaparthy, Telangana,India"
print ("Name:{}\nAge:{}\naddress:{}".format (name,age, address))

Name:Adil
Age:19
address:wanaparthy, Telangana,India


In [ ]:
#pattern
bj1=5
for i in range(1,6):
  for J1 in range(i):
    print (bj1,end="")
  bj1-=1
  print("")

5
44
333
2222
11111


In [ ]:
#character
cj1=input("Adil Enter the character: ")
if cj1>='0' and cj1<='9':
 print("Digit")
elif cj1.isupper():
 print("Upper case characters")
elif cj1.islower():
 print ("Lower case characters")
else:
 print("special characters")

Adil Enter the character: 3
Digit


In [ ]:
nj1=int(input("Adil how many bo of elements"))
aj1=0
bj1=1
print (aj1,bj1,end="")
i=2
while (i<nj1):
  sum=aj1+bj1
  print (sum,end="")
  aj1=bj1
  bj1=sum
  i+=1

Adil how many bo of elements7
0 112358

In [ ]:

#prime number
lj1=1
uj1=10
print("Adil The Prime number between",lj1,"and",uj1,"are:")
for num in range(lj1,uj1+1):
  if num>1:
    for i in range(2,num):
      if (num%i)==0:
        break
    else :
      print(num)

Adil The Prime number between 1 and 10 are:
2
3
5
7


In [ ]:
#list,tuple to array
import numpy as j1
my_list_j1=[1,2,3,4,5,6,7,8,9]
print("Adil list to array is:")
print(j1.asarray(my_list_j1))
my_tuple_j1=([8,5,6],[4,6,4])
print("Adil tuple to array is:")
print(j1.asarray(my_tuple_j1))

Adil list to array is:
[1 2 3 4 5 6 7 8 9]
Adil tuple to array is:
[[8 5 6]
 [4 6 4]]


In [ ]:

#common values between two arrays
import numpy as J1
arr_j1=J1.array([0,10,20,40,60])
print("Adil array-1 is:",arr_j1)
array_j1=[30,40,60]
print("Adil array-2 is:",array_j1)
print ("common values between two arrays is:")
print (J1.intersect1d(arr_j1,array_j1))

Adil array-1 is: [ 0 10 20 40 60]
Adil array-2 is: [30, 40, 60]
common values between two arrays is:
[40 60]


In [ ]:
#Gcd of two numbers using function
def gcdj1(num_j1,num_j2):
  a=num_j1
  b=num_j2
  while num_j1!=num_j2:
    if num_j1>num_j2:
      num_j1-=num_j2
    else :
      num_j2-=num_j1
  return num_j1
print("Adil The Gcd of ",a,"and",b,"is :",gcdj1(40,80))

Adil The Gcd of  0 and 0 is : 40


In [ ]:
def p(s):
  return s_j1==s_j1[::-1]
s_j1="case"
ans_j1=p(s_j1)
if ans_j1:
    print("Yes Adil")
else :
     print("No Adil")

No Adil


In [ ]:
#sorted list
def is_sorted (list_j1):
  if sorted (list_j1)==list_j1:
    return True
  else :
    return False
print(is_sorted([1,3,2]))
print(is_sorted([1,2,1,2]))
print(is_sorted([]))
print(is_sorted(['b','a']))

False
False
True
False


In [ ]:
#Sorting the list
test_list_j1=[1,4,6,7,9]
print("original list :" +str(test_list_j1))
flag=0
i=1
while i<len(test_list_j1):
  if (test_list_j1[i] < test_list_j1[i-1]):
    flag=1
  i=i+1
if (not flag):
  print ("yes Adil the list is sorted ")
else :
  print ("No Adil the list is sorted ")

original list :[1, 4, 6, 7, 9]
