<a href="https://colab.research.google.com/github/AdilGhub/pycode/blob/main/Sk_adil_j1_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

#palindrome
def pal():
  i=454
  rev=0
  temp=i
  while i!=0:
    rem=i%10
    rev=rev*10+rem
    i//=10
  if temp==rev:
     print("palindrome")
  else :
    print(" not palindrome")

In [ ]:
pal()

palindrome


In [ ]:
#palindrome
def pal(i):
 # i=int(input("enter the number"))
  rev=0
  temp=i
  while i!=0:
    rem=i%10
    rev=rev*10+rem
    i//=10
  if temp==rev:
     print("paliandrome")
  else :
    print(" not paliandrome")

In [ ]:
pal(656)

paliandrome


In [ ]:
#palaindrome
def pal(i):
  #i=int(input("enter the number"))
  rev=0
  temp=i
  while i!=0:
    rem=i%10
    rev=rev*10+rem
    i//=10
  return temp,rev

In [ ]:
x,y=pal(565)
if x==y:
     print("paliandrome")
else :
    print(" not paliandrome")

paliandrome


In [ ]:
#Factorial
def fact():
 j1=5
 f=1
 i=1
 while i<=j1:
   f=f*i
   i=i+1
 print (f)

In [ ]:
fact()

120


In [ ]:
#Factorial
def fact(j1):
 f=1
 i=1
 while i<=j1:
   f=f*i
   i=i+1
 print (f)

In [ ]:
fact(4)

24


In [ ]:
#Factorial
def fact(j1):
 f=1
 i=1
 while i<=j1:
   f=f*i
   i=i+1
 return f

In [ ]:
fact(6)

720

In [ ]:

#Armstrong numbers
def arm():
  i=371
  sum=0
  temp=i
  while i!=0:
    rem=i%10
    sum=sum+(rem*rem*rem)
    i//=10
  if temp==sum:
     print("Armstrong number")
  else :
    print(" not a Armstrong number")

In [ ]:
arm()

Armstrong number


In [ ]:

#Armstrong numbers
def arm(i):
  sum=0
  temp=i
  while i!=0:
    rem=i%10
    sum=sum+(rem*rem*rem)
    i//=10
  if temp==sum:
     print("Armstrong number")
  else :
    print(" not a Armstrong number")

In [ ]:
arm(371)

Armstrong number


In [ ]:

#Armstrong numbers
def arm(i):
  i=371
  sum=0
  temp=i
  while i!=0:
    rem=i%10
    sum=sum+(rem*rem*rem)
    i//=10
  return temp,sum

In [ ]:
x,y=arm(371)
if x==y:
     print("Armstrong number")
else :
    print(" not a Armstrong number")

Armstrong number


In [ ]:
#prime number
def prime():
  j1=3
  i=1
  c=0
  while i<=j1:
    if j1%i==0:
      c=c+1
    i=i+1
  if c==2:
     print("prime number")
  else:
     print("Not a prime number")

In [ ]:
prime()

prime number


In [ ]:
#prime number
def prime():
  j1=3
  i=1
  c=0
  while i<=j1:
    if j1%i==0:
      c=c+1
    i=i+1
  if c==2:
     print("prime number")
  else:
     print("Not a prime number")

In [ ]:
prime(5)

prime number


In [ ]:
#prime number
def prime(j1):
  i=1
  c=0
  while i<=j1:
    if j1%i==0:
      c=c+1
    i=i+1
  return c

In [ ]:
x=prime(
if x==2:
     print("prime number")
else:
     print("Not a prime number")

prime number


In [ ]:
#DICTIONARY
def mar():
  marvel={"1":"iron man","2":"Hulk","3":"Thor","4":"Falcon"}
  MC={0:"captain America",1:"Hawkeye"}
  print (marvel)

#Adding of characters
  marvel["5"]="Captain America"
  print ("updated dictionary:",marvel)

#sorting of dictionary
  print(sorted(marvel,reverse=True))

#delete & pop item
  del marvel["2"]
  marvel.popitem()#Last item deleted
  print (marvel)

#copy Dict
  M=marvel.copy()
  print (M)

#length of the dictionary
  print("length of dict is",len(marvel))

#type
  print(type(marvel))

#All and any
  print(all(marvel))
  print(any(MC))
  print(all(MC))

#keys
  Marvel={"M","A","R","V","E","L"}
  Value="character"
  characters=dict.fromkeys(Marvel,Value)
  print (characters)

#append
  Marvel={"M","A","R","V","E","L"}
  Value=["J"]
  characters=dict.fromkeys(Marvel,Value)
  print (characters)
  Value.append(1)
  print(characters)

#Get method
  print("Best character of marvel is:",marvel.get("1"))

#items
  J=marvel.items()
  print(J)
  del [marvel["4"]]
  print("update item:",J)

#inserting the character
  marvel["6"]="Spiderman"
  print (marvel)

#clear method
  marvel.clear()
  print(marvel)

In [ ]:
#SETS
def mar1():
  MC={"iron man","Hulk","Thor","captain America", "Hawkeye ","Black widow","spider man"}
  print (MC)

#adding the elements to set
  MC.add("Loki")
  print (MC)

#adding of sets
  MM=["Loki","Thanos"]
  MC.update(MM)
  print(MC)

#length of set
  print("Total elements:",len(MC))

#union
  J1={"iron man","Hulk", "Loki","Thor"}
  J2={ "Loki","Thanos","Ultron"}
  print ("union operations :",J1|J2)

#Intersection
  print ("Intersection operations:",J1&J2)

#Difference of set
  print("Difference: ",J1-J2)

#Set symmetric
  print("set symmetric:",J1^J2)

#sub set
  J3={"iron man","Thor"}
  print(J3.issubset(J1))

#disjoint
  print(J3.isdisjoint(J2))

#empty set
  Set=set()

#type
  print (type(MC))

In [ ]:
mar1()

{'Black widow', 'iron man', 'Hawkeye ', 'captain America', 'Hulk', 'Thor', 'spider man'}
{'Black widow', 'iron man', 'Hawkeye ', 'captain America', 'Hulk', 'Thor', 'Loki', 'spider man'}
{'Black widow', 'Thanos', 'spider man', 'Loki', 'Hulk', 'Thor', 'iron man', 'Hawkeye ', 'captain America'}
Total elements: 9
union operations : {'iron man', 'Thanos', 'Hulk', 'Thor', 'Loki', 'Ultron'}
Intersection operations: {'Loki'}
Difference:  {'Thor', 'iron man', 'Hulk'}
set symmetric: {'Thanos', 'Hulk', 'Ultron', 'Thor', 'iron man'}
True
True
<class 'set'>


In [ ]:
# LIST ABOUT MARVEL
def mar3():
  marvel=["iron man","hawkeye","captain america","black widow","thor"]
  MC={"iron man","Hulk","Thor","captain America", "Hawkeye ","Black widow","spider man"}
  print (MC)
  print(marvel[1:4])
  print(marvel[-4:-1])
  print(marvel[:-1])

#adding element
  marvel.append("spider man")
  marvel.insert(1,"Hulk")
  print(marvel)

#deleting element
  del marvel[3]
  marvel.pop(1)
  marvel.remove("thor")
  print(marvel)

#sorting
  marvel.sort()
  marvel.sort(reverse=True)
  print(marvel)

#Adding 0f lists
  MC=['loki', 'thanos', 'ultron', 'docter doom']
  marvel.extend(MC)
  print(marvel)

#list comprehension
  for i,element in enumerate(marvel):
    print(i,":",element)

#Extend
  marvel.extend(MC)
  print("list after extend :",marvel)

#copy
  j1=marvel.copy()
  print('copied list:',j1)

#type
  print(type(marvel))

#clearing the list
  marvel.clear()
  print(marvel)

In [ ]:
def mav2():
  marvel='black widow', 'hawkeye', 'iron man', 'spider man', 'thor', 'loki', 'thanos', 'ultron', 'docter doom'
  print(marvel[1:4])
  print(marvel[-4:-1])
  print(marvel[:-1])
  print(marvel[1:])
  print(marvel[-8:8])
  print(marvel[0:-1])

#tuple with mixed data types
  Mm=(1,"Adil",30)
  print (Mm)

#nested tuple
  m=("thor",[1,4,7],(1,8,0))
  print(m)

#type
  print(type(marvel))

#creating tuple with one element
  mar="hella",
  print(type(mar))

In [ ]:
import numpy as np
X=[[1,2,3],
   [4,5,6],
   [7,8,9]]
Y=[[1,2,3],
   [4,5,6],
   [7,8,9]]
result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
#for i in range(len(X)):
  #for j in range(len(Y[0])):
     #for k in range(len(Y)):
        #result [i][j]+=X[i][j]*Y[k][j]
#for r in result:
  #print (r)
result=np.dot(X,Y)
for r in result:
   print(r)

[30 36 42]
[66 81 96]
[102 126 150]


In [ ]:
x=5
y='hello'
try:
  z=x+y
except TypeError:
  print ("sorry")

sorry


In [ ]:
class A:
  def display(self):
    print("parent")
class B(A):
  def dis(self):
    print("child")
ob=B()
ob.dis()
ob.display()

child
parent
